apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
    tag: {{ .Values.image.tag }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.app.name }}
    tag: {{ .Values.image.tag }}
  type: {{ .Values.service.type }}
